# Generated by Django 3.2 on 2021-04-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['name', 'codename'], 'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
    ]
