# Generated by Django 3.2 on 2021-04-22 11:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, help_text='用户头像', null=True, upload_to=users.models.PathAndRename('avatar/2021-04-22/'), verbose_name='用户头像'),
        ),
    ]
